//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautySalonWpf.AdoModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppointmentsServices
    {
        public int id { get; set; }
        public Nullable<int> appointmentId { get; set; }
        public Nullable<int> serviceId { get; set; }
    
        public virtual Appointments Appointments { get; set; }
        public virtual Services Services { get; set; }
    }
}
