//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautySalonWpf.AdoModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BeautySalonEntities : DbContext
    {
        public BeautySalonEntities()
            : base("name=BeautySalonEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminNotifications> AdminNotifications { get; set; }
        public virtual DbSet<Admins> Admins { get; set; }
        public virtual DbSet<Appointments> Appointments { get; set; }
        public virtual DbSet<AppointmentsServices> AppointmentsServices { get; set; }
        public virtual DbSet<AppointmentStatus> AppointmentStatus { get; set; }
        public virtual DbSet<ClientNotifications> ClientNotifications { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Delivery> Delivery { get; set; }
        public virtual DbSet<History> History { get; set; }
        public virtual DbSet<MasterNotifications> MasterNotifications { get; set; }
        public virtual DbSet<Masters> Masters { get; set; }
        public virtual DbSet<MastersQualifications> MastersQualifications { get; set; }
        public virtual DbSet<MastersSkills> MastersSkills { get; set; }
        public virtual DbSet<na_vsyakiy> na_vsyakiy { get; set; }
        public virtual DbSet<ProductReceiveRequest> ProductReceiveRequest { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<Provider> Provider { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<ServiceRunTime> ServiceRunTime { get; set; }
        public virtual DbSet<Services> Services { get; set; }
        public virtual DbSet<ServiceSkill> ServiceSkill { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TypeProducts> TypeProducts { get; set; }
        public virtual DbSet<TypeServices> TypeServices { get; set; }
        public virtual DbSet<MastersSalaries> MastersSalaries { get; set; }
    }
}
