//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautySalonWpf.AdoModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceRunTime
    {
        public int runTimeId { get; set; }
        public Nullable<int> juniorRunTime { get; set; }
        public Nullable<int> middleRunTime { get; set; }
        public Nullable<int> SeniorRunTime { get; set; }
    }
}
