//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautySalonWpf
{
    using System;
    using System.Collections.Generic;
    
    public partial class CancelledAppointments
    {
        public int id { get; set; }
        public Nullable<int> masterId { get; set; }
        public Nullable<System.TimeSpan> timeStart { get; set; }
        public Nullable<System.TimeSpan> timeEnd { get; set; }
        public Nullable<int> totalSum { get; set; }
        public Nullable<int> totalDuration { get; set; }
        public Nullable<int> statusId { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> clientId { get; set; }
    }
}
