//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautySalonWpf
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients
    {
        public int userID { get; set; }
        public string Lname { get; set; }
        public string FName { get; set; }
        public Nullable<System.DateTime> dateBirth { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string photo { get; set; }
        public string Preferences { get; set; }
        public int roleId { get; set; }
        public Nullable<int> visitsCount { get; set; }
    
        public virtual Roles Roles { get; set; }
    }
}
