//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautySalonWpf
{
    using System;
    using System.Collections.Generic;
    
    public partial class Delivery
    {
        public int deliveryId { get; set; }
        public Nullable<int> productId { get; set; }
        public Nullable<int> productCount { get; set; }
        public Nullable<int> providerId { get; set; }
    
        public virtual Prodiver Prodiver { get; set; }
        public virtual Products Products { get; set; }
    }
}
