//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautySalonWpf
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public int productId { get; set; }
        public string name { get; set; }
        public Nullable<int> price { get; set; }
        public string photo { get; set; }
        public Nullable<int> typeId { get; set; }
    
        public virtual TypeProducts TypeProducts { get; set; }
    }
}
