//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautySalonWpf
{
    using System;
    using System.Collections.Generic;
    
    public partial class Services
    {
        public int serviceId { get; set; }
        public string serviceName { get; set; }
        public Nullable<int> typeServiceId { get; set; }
        public Nullable<int> juniorRunTime { get; set; }
        public Nullable<int> middleRunTime { get; set; }
        public Nullable<int> SeniorRunTime { get; set; }
        public Nullable<int> juniorPrice { get; set; }
        public Nullable<int> middlePrice { get; set; }
        public Nullable<int> seniorPrice { get; set; }
    
        public virtual TypeServices TypeServices { get; set; }
    }
}
