//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautySalonWpf
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceSkill
    {
        public int id { get; set; }
        public Nullable<int> serviceId { get; set; }
        public Nullable<int> skillId { get; set; }
        public Nullable<int> runTime { get; set; }
        public Nullable<int> price { get; set; }
    
        public virtual MastersSkills MastersSkills { get; set; }
        public virtual Services Services { get; set; }
    }
}
